project:
  type: website
  output-dir: build/site
  render:
    - index.qmd
    - docs/
    - adoc-pages/

website:
  title: "quarto-plus"
  site-url: https://watanabe3tipapa.github.io/quarto-plus/
  navbar:
    left:
      - href: index.html
        text: Home
      - href: docs/tutorial.html
        text: Tutorial
      - href: docs/templates/index.html
        text: Templates
      - href: docs/index.html
        text: Docs

metadata-files: []
